name       : libxmlb
version    : 0.3.12
release    : 4
source     :
    - https://github.com/hughsie/libxmlb/archive/refs/tags/0.3.12.tar.gz : ba96f90e41d3a0bca42a32c3d239458016f6861cc1023bccf1a517a39406241e
homepage   : https://github.com/hughsie/libxmlb
license    :
    - LGPL-2.1-or-later
    - GPL-2.0-or-later
component  : programming.library
summary    : A library to help create and query binary XML blobs
description: |
    XML is slow to parse and strings inside the document cannot be memory mapped as they do not have a trailing NUL char. The libxmlb library takes XML source, and converts it to a structured binary representation with a deduplicated string table -- where the strings have the NULs included.
builddeps  :
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - libstemmer-devel
setup      : |
    %meson_configure \
        -Dgtkdoc=false \
        -Dstemmer=true
build      : |
    %ninja_build
install    : |
    %ninja_install
